name: Dispatch to QA repo

on:
  push:
    branches:
      - main  # Only on push to 'stage' branch

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger QA repo workflow
        run: |
          curl -X POST https://api.github.com/repos/Sivakumarr7/php-docker/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.QA_REPO_PAT }}" \
            -d '{"event_type":"trigger-from-dev-repo"}'
